name: "[DEV] CI/CD Auth Provider API"

on:
  push:
    branches:
      - dev

env:
  APP_NAME: bitsoft-auth
  APP_VERSION: "v1.0.0-beta"
  NETWORK: auth-provider

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: 'Build Inventory Image'
        run: |
          docker build . -t ghcr.io/${{ secrets.GHCR_USERNAME }}/${APP_NAME}:${APP_VERSION}

      - name: 'Push Inventory Image to GitHub Container Registry'
        run: |
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/${APP_NAME}:${APP_VERSION}

#      - name: 'Push Inventory Image to Docker Hub'
#        run: |
#          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
#          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${APP_NAME}:${APP_VERSION}